INSERT INTO vets VALUES (1, 'James', 'Carter');
INSERT INTO vets VALUES (2, 'Helen', 'Leary');
INSERT INTO vets VALUES (3, 'Linda', 'Douglas');
INSERT INTO vets VALUES (4, 'Rafael', 'Ortega');
INSERT INTO vets VALUES (5, 'Henry', 'Stevens');
INSERT INTO vets VALUES (6, 'Sharon', 'Jenkins');
INSERT INTO vets VALUES (7, 'Harry', 'Stone');
INSERT INTO vets VALUES (8, 'Larry', 'Roughe');
INSERT INTO vets VALUES (9, 'Tina', 'Lash');
INSERT INTO vets VALUES (10, 'Thomas', 'Oneil');
INSERT INTO vets VALUES (11, 'Carl', 'Black');
INSERT INTO vets VALUES (12, 'Steve', 'Howly');
INSERT INTO vets VALUES (13, 'Henry', 'Stevenson');
INSERT INTO vets VALUES (14, 'Peter', 'Svensson');
INSERT INTO vets VALUES (15, 'Mary', 'Cost');
INSERT INTO vets VALUES (16, 'Judy', 'Ortega');
INSERT INTO vets VALUES (17, 'Lisa', 'Harrison');
INSERT INTO vets VALUES (18, 'Cathrine', 'Rocky');
INSERT INTO vets VALUES (19, 'Tim', 'Taylor');
INSERT INTO vets VALUES (20, 'Elon', 'Harvest');
INSERT INTO vets VALUES (21, 'Barney', 'Thorn');
INSERT INTO vets VALUES (22, 'Pete', 'Peterson');
INSERT INTO vets VALUES (23, 'Arturo', 'Onolo');
INSERT INTO vets VALUES (24, 'Cristy', 'Fricks');


INSERT INTO specialties VALUES (1, 'radiology');
INSERT INTO specialties VALUES (2, 'surgery');
INSERT INTO specialties VALUES (3, 'dentistry');
INSERT INTO specialties VALUES (4, 'general');
INSERT INTO specialties VALUES (5, 'pediatry');
INSERT INTO specialties VALUES (6, 'eyes');
INSERT INTO specialties VALUES (7, 'dermatology');
INSERT INTO specialties VALUES (8, 'nesthesiologists');
INSERT INTO specialties VALUES (9, 'internal');
INSERT INTO specialties VALUES (10, 'cardiology');
INSERT INTO specialties VALUES (11, 'diets');
INSERT INTO specialties VALUES (12, 'endriconolgy');
INSERT INTO specialties VALUES (13, 'infections');
INSERT INTO specialties VALUES (14, 'ophthalmology');
INSERT INTO specialties VALUES (15, 'otolaryngology');
INSERT INTO specialties VALUES (16, 'pulmonologist');
INSERT INTO specialties VALUES (17, 'neurology');
INSERT INTO specialties VALUES (18, 'oncology');
INSERT INTO specialties VALUES (19, 'allergist');
INSERT INTO specialties VALUES (20, 'immunity');
INSERT INTO specialties VALUES (21, 'microbiology');
INSERT INTO specialties VALUES (22, 'neurosurgeon');
INSERT INTO specialties VALUES (23, 'ENT');
INSERT INTO specialties VALUES (24, 'psychiatrist');

INSERT INTO vet_specialties VALUES (2, 1);
INSERT INTO vet_specialties VALUES (3, 2);
INSERT INTO vet_specialties VALUES (3, 3);
INSERT INTO vet_specialties VALUES (4, 2);
INSERT INTO vet_specialties VALUES (5, 12);
INSERT INTO vet_specialties VALUES (6, 10);
INSERT INTO vet_specialties VALUES (7, 7);
INSERT INTO vet_specialties VALUES (8, 8);
INSERT INTO vet_specialties VALUES (9, 21);
INSERT INTO vet_specialties VALUES (10, 9);
INSERT INTO vet_specialties VALUES (11, 2);
INSERT INTO vet_specialties VALUES (12, 1);
INSERT INTO vet_specialties VALUES (13, 3);
INSERT INTO vet_specialties VALUES (14, 3);
INSERT INTO vet_specialties VALUES (15, 1);
INSERT INTO vet_specialties VALUES (16, 2);
INSERT INTO vet_specialties VALUES (17, 14);
INSERT INTO vet_specialties VALUES (18, 15);
INSERT INTO vet_specialties VALUES (19, 1);
INSERT INTO vet_specialties VALUES (20, 1);
INSERT INTO vet_specialties VALUES (21, 2);
INSERT INTO vet_specialties VALUES (22, 3);
INSERT INTO vet_specialties VALUES (23, 1);
INSERT INTO vet_specialties VALUES (24, 2);
INSERT INTO vet_specialties VALUES (24, 1);
